### ISSUE TITLE
Update README dependencies

### ISSUE THREAD

**Issue by mcherep** [aggelgian/cuter#126]
PropEr isn't an optional dependency:

```bash
$ ./configure --with-python=/usr/bin/python

configure: Meck is missing. You will not be able to run the tests. 
Download it at https://github.com/eproxus/meck.
configure: error: PropEr is missing. You will not be able to run the tests. 
Download it at https://github.com/manopapad/proper and follow the instructions.
```

It worked once I added PropEr to Erlang's path.
GPB (https://github.com/tomas-abrahamsson/gpb) is a required dependency or it fails:

```bash
$ make depend

rm -f .depend
PROTOC-ERL cuter_proto_erlang_term.proto
/bin/bash: /bin/protoc-erl: No such file or directory
make: *** [Makefile:161: src/cuter_proto_erlang_term.erl] Error 127
```
It worked once I cloned GPB and built it.
Finally, to make it work my configure command looked like this:

```bash
./configure --with-python=/usr/bin/python --with-protoc=$PWD/lib/protoc-3.2.0/bin/protoc 
--with-gpb=/full/path/to/gpb

configure: Meck is missing. You will not be able to run the tests. 
Download it at https://github.com/eproxus/meck.
configure: creating ./config.status
config.status: creating Makefile

CutEr was configured with success.
Erlang Compiler:    erlc
Python:             /usr/bin/python
protoc:             /full/path/to/cuter/lib/protoc-3.2.0/bin/protoc
Z3Py:               yes
protobuf (Python):  yes
Meck:               no
PropEr:             yes
GPB:                yes

To build CutEr, execute:
  make depend
  make
```

**Comment by albertnetymk** [comment]
I had exactly the same issue on following the readme. The steps above resolve the problem.

**Comment by ioolkos** [comment]
Apologies for hi-jacking the issue, but wanted to say that I enjoyed your paper on cuter, @mcherep. Thanks for it!
Also, huge thank you to @aggelgian and @kostis for this incredible piece of software, using it feels like from the future :)
(I should and will use it more again, I hope)

**Comment by kostis** [comment]
Thanks for the comments and feedback on this issue.

Since this issue was opened, `meck` has been taken out as a dependency, and `PropEr` is now considered optional by the configure script.  I will therefore close this issue.

Please re-open a new one if there are still discrepancies between what the README specifies and your experiences in your build environment.
