### ISSUE TITLE
Introduce an option to append directories to code path

### ISSUE THREAD

**Issue by aggelgian** [aggelgian/cuter#14]
Support an option similar to Erlang's `-pa` flag.

A scenario that this is needed:

```erlang
-module(foo).
-export([f/1]).

-spec f(bar:t()) -> ok.
f(_) -> ok.
```

and the module `bar` is not loaded.

**Comment by kostis** [comment]
Sure, but we also need it even for:
<pre>f() -> bar:g().</pre>
where module `bar` is not loaded nor on the default path of the loader.
