### ISSUE TITLE
Printing of UNSUPPORTED MFAS

### ISSUE THREAD

**Issue by kostis** [aggelgian/cuter#20]
Currently MFAs encountered during execution whose code is not in Erlang -- these are actually called BIFs in the Erlang lingo -- are not printed by default but only when the `-v` option is on.

Enable their printing by default at the end of the execution, after the list of inputs that cause errors, and introduce a command line option of the cuter script to suppress this.

Also, make sure that MFAs of modules that are whitelisted are never included in the unsupported list.

**Comment by aggelgian** [comment]
This is a sample output after b642a4a

```
Testing bar:f/1 ...
.
bar:f(42)

INPUTS THAT LEAD TO RUNTIME ERRORS
#1 bar:f(42)
UNSUPPORTED MFAS
  erlang:'bsl'/2
```

**Comment by kostis** [comment]
Looks OK, but I would not mind a blank line after the last erroneous input as a separator.
Alternatively, something more fancy like:
```
=== INPUTS THAT LEAD TO RUNTIME ERRORS ===
#1 bar:f(42)
=== UNSUPPORTED MFAS ===
  erlang:'bsl'/2
```
may also be OK (better?)

**Comment by aggelgian** [comment]
A combination of both seems better.
```
aggelgian@lambda:~/git-repos/cuter$ cuter bar f '[4]'
Testing bar:f/1 ...
.
bar:f(42)

=== INPUTS THAT LEAD TO RUNTIME ERRORS ===
#1 bar:f(42)

=== UNSUPPORTED MFAS ===
erlang:'bsl'/2
```
I'll implement this one.
