### ISSUE TITLE
Support 'erlang:phash/2', 'erlang:trunc/1', 'erlang:get/1' and 'erlang:put/2'

### ISSUE THREAD

**Issue by mcherep** [aggelgian/cuter#68]
Code example

```erlang
-spec test_02(Proplist :: [{atom(), atom()}]) -> atom().
test_02([]) ->
  ok;
test_02(Proplist) ->
  Keys = proplists:get_keys(Proplist),
  Index = random:uniform(length(Keys)),
  lists:nth(Index, Keys).
```

=== BIFs Currently without Symbolic Interpretation ===
erlang:phash/2
erlang:trunc/1
erlang:get/1
erlang:put/2

**Comment by kostis** [comment]
Thanks for the example, but most of these have been reported as issues #52, #56 and #57.

**Comment by kostis** [comment]
I am closing this issue.  The part that is not mentioned in other issues (support `erlang:trunc/1`) is fixed.
