### ISSUE TITLE
Erroneous runtime error reported

### ISSUE THREAD

**Issue by kostis** [aggelgian/cuter#86]
Consider the following command against the module below:
<pre>cuter uni to_upper '[[]]' -r -d 4</pre>
If the first clause of `to_upper/1` is commented out, CutEr reports no error, as it should: 
<pre>Compiling uni.erl ... OK
Testing uni:to_upper/1 ...
.x.x..xxx...
No Runtime Errors Occured</pre>
However, if one uncomments this clause, execution erroneously reports:
<pre>Compiling uni.erl ... OK
Testing uni:to_upper/1 ...
uni:to_upper([])
xx
=== Inputs That Lead to Runtime Errors ===
#1 uni:to_upper([])</pre>
which is weird because this call does not fail.

```erl
-module(uni).
-export([to_upper/1]).

-spec to_upper(string()) -> string().
%% to_upper(S) when is_binary(S) ->
%%   unicode:characters_to_binary(to_upper(unicode:characters_to_list(S)));
to_upper(S) when is_list(S) ->
  [char_to_upper(C) || C <- S];
to_upper(C) when is_integer(C) ->
  char_to_upper(C).

char_to_upper(16#0061) -> 16#0041;
char_to_upper(16#0062) -> 16#0042;
char_to_upper(C) -> C.
```

**Comment by aggelgian** [comment]
This false report is due to the fact that CutEr crashes on that execution with `{primop_not_supported,bs_context_to_binary}`.

The first step we should do would be not to report such crashes as errors, but we will ultimately need to tackle at least the most common primops.
