### ISSUE TITLE
Update tests to work for Z3 4.4.2

### ISSUE THREAD

**Issue by aggelgian** [aggelgian/cuter#94]
Some unit and functional tests fail when using Z3 v4.4.2 instead of v4.4.1.

The model in those testcases is too general and the problem is that solver chooses another valid solution.
The tests need to be made aware of the version of the underlying solver.

**Comment by kostis** [comment]
I suggest we wait a bit with this issue.  While it's pretty clear that different versions of z3 may be returning different solutions to our tests, this particular one is not officially out yet. (Tt's just the behaviour of the current `master` branch of z3 we are witnessing here.)

Anyway, when we hook different solvers to CutEr, we will need to find a more general way of dealing with solutions from different solvers and their versions anyway. So I suggest we postpone dealing with this issue till then.
